### PR TITLE
Fixes imageResponseBytes

### PR DESCRIPTION
**Pull request by joedawson**
This fixes the ability to get `imageResponseBytes`.

### CODE REVIEW

**Comment by dsentker** [comment]
Thank you very much!

**Comment by joedawson** [comment]
No problem, thank you very much for this package :)

Could you tag a release please?

**Comment by dsentker** [comment]
Done :)

**Comment by joedawson** [comment]
Thank you @dsentker, I don't suppose you could also update on packagist too? https://packagist.org/packages/dsentker/phpinsights

**Comment by dsentker** [comment]
Should be synced now.. :)

**Pull request merged**
